//! Per-family construction dispatch for model providers.
//!
//! Each `<Family>ModelProviderConfig` typed slot from
//! `zeroclaw-config::providers::ModelProviders` implements
//! `FamilyProviderFactory`, which declares the family's endpoint behavior and
//! builds its runtime provider.
//!
//! Dispatch is generated by [`for_each_model_provider_slot!`] — the same
//! macro that defines the typed slots is the only place the family list
//! lives. Adding a family is one slot row plus one trait impl; missing the
//! impl fails to compile when the dispatch is generated.
//!
//! [`for_each_model_provider_slot!`]: zeroclaw_config::for_each_model_provider_slot

use crate::ModelProviderRuntimeOptions;
use crate::compatible::{AuthStyle, OpenAiCompatibleModelProvider};
use crate::traits::ModelProvider;
use anyhow::Result;

const OLLAMA_COMPAT_DEFAULT_URL: &str = "http://localhost:11434/v1";

/// Family-level endpoint behavior when no operator alias is available.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ProviderEndpoint {
    /// The family has one stable default endpoint.
    Fixed(&'static str),
    /// The endpoint depends on region, credentials, discovery, or runtime state.
    Dynamic,
    /// The operator must configure an endpoint before construction.
    OperatorRequired,
    /// The family invokes a CLI rather than an HTTP model endpoint.
    CliBacked,
}

impl ProviderEndpoint {
    #[must_use]
    /// Return the stable URL only for [`ProviderEndpoint::Fixed`].
    pub const fn fixed_url(self) -> Option<&'static str> {
        match self {
            Self::Fixed(url) => Some(url),
            Self::Dynamic | Self::OperatorRequired | Self::CliBacked => None,
        }
    }
}

pub(crate) trait FamilyProviderFactory {
    const ENDPOINT: ProviderEndpoint;

    fn create_provider(
        &self,
        alias: &str,
        key: Option<&str>,
        api_url: Option<&str>,
        opts: &ModelProviderRuntimeOptions,
    ) -> Result<Box<dyn ModelProvider>>;

    fn fallback_auth_ready(&self, key: Option<&str>, _opts: &ModelProviderRuntimeOptions) -> bool {
        has_api_key(key)
    }
}

fn fixed_family_endpoint<T: FamilyProviderFactory>() -> &'static str {
    // INVARIANT: this helper is called only by factory implementations whose
    // associated endpoint is declared `Fixed`; registry tests enumerate the
    // canonical families and enforce that classification.
    T::ENDPOINT
        .fixed_url()
        .expect("fixed endpoint helper requires a fixed provider family")
}

fn has_api_key(key: Option<&str>) -> bool {
    has_non_empty_value(key)
}

fn has_non_empty_value(value: Option<&str>) -> bool {
    value.map(str::trim).is_some_and(|value| !value.is_empty())
}

/// Merge the config-driven request-body extras into a single object that the
/// compat builder flattens onto the top level of every request.
///
/// - `provider_extra` supplies arbitrary top-level keys. Only object-shaped
///   JSON is threaded through; other shapes are dropped here (and warned about
///   by the caller).
/// - `chat_template_kwargs` is nested under its own `chat_template_kwargs` key,
///   matching what chat-template-aware backends (vLLM, SGLang, llama.cpp)
///   expect. Only object-shaped JSON is threaded through, mirroring
///   `provider_extra`; other shapes are dropped here (and warned about by the
///   caller).
///
/// Returns `None` when neither source contributes anything, so the caller can
/// skip setting `extra_body` entirely.
fn merge_extra_body(
    provider_extra: Option<&serde_json::Value>,
    chat_template_kwargs: Option<&serde_json::Value>,
) -> Option<serde_json::Value> {
    let mut merged = serde_json::Map::new();
    if let Some(obj) = provider_extra.and_then(serde_json::Value::as_object) {
        merged.extend(obj.clone());
    }
    if let Some(kwargs) = chat_template_kwargs.filter(|v| v.is_object()) {
        merged.insert("chat_template_kwargs".to_string(), kwargs.clone());
    }
    (!merged.is_empty()).then_some(serde_json::Value::Object(merged))
}

/// Apply cross-cutting compat overrides (timeout, headers, api_path,
/// max_tokens, reasoning effort, TLS CA, `provider_extra`,
/// `chat_template_kwargs`) to a compat builder before calling `.build()` and
/// boxing the trait object. Single source of the override chain — every compat
/// impl funnels through here.
pub fn apply_compat_options(
    mut b: crate::compatible::OpenAiCompatibleBuilder,
    opts: &ModelProviderRuntimeOptions,
) -> Box<dyn ModelProvider> {
    if let Some(t) = opts.provider_timeout_secs {
        b = b.timeout_secs(t);
    }
    if let Some(ref effort) = opts.reasoning_effort {
        b = b.reasoning_effort(Some(effort.clone()));
    }
    if opts.reasoning_effort_passthrough {
        b = b.with_reasoning_effort_passthrough();
    }
    if !opts.extra_headers.is_empty() {
        b = b.extra_headers(opts.extra_headers.clone());
    }
    if opts.api_path.is_some() {
        b = b.api_path(opts.api_path.clone());
    }
    if let Some(mt) = opts.provider_max_tokens {
        b = b.max_tokens(Some(mt));
    }
    if let Some(ref cert_path) = opts.tls_ca_cert_path {
        b = b.tls_ca_cert_path(cert_path);
    }
    b = b.tool_result_image_policy(opts.tool_result_image_policy);
    if opts.replay_assistant_reasoning == Some(false) {
        b = b.without_assistant_reasoning_replay();
    }
    if opts.thinking_passthrough {
        b = b.with_thinking_passthrough();
    }
    // The configured `[multimodal]` policy. Without this the provider boundary
    // would re-normalize already-prepared messages under defaults and could
    // trim images the runtime had accepted under the operator's settings.
    b = b.multimodal(opts.multimodal.clone());
    if opts.cache_passthrough {
        b = b.with_cache_passthrough();
    }
    if let Some(cache_ttl) = opts.cache_ttl {
        b = b.with_cache_ttl(cache_ttl);
    }
    // `provider_extra` alias is captured before `build()` because the WARN
    // path below reads it for logging. Only object-shaped JSON is threaded
    // through; other shapes produce a WARN and are ignored (matching the
    // pre-refactor behaviour).
    //
    // `chat_template_kwargs` is folded into the same `extra_body` object under
    // its own top-level key, so a chat-template payload rides the request body
    // even when `provider_extra` is unset. The builder exposes a single
    // `extra_body` slot, hence the merge here rather than two setter calls.
    if let Some(extra) = merge_extra_body(
        opts.provider_extra.as_ref(),
        opts.chat_template_kwargs.as_ref(),
    ) {
        b = b.extra_body(extra);
    }
    let p = b.build();
    if let Some(extra) = &opts.provider_extra
        && !extra.is_object()
    {
        let config_path = format!("[providers.models.{}].provider_extra", p.alias);
        ::zeroclaw_log::record!(
            WARN,
            ::zeroclaw_log::Event::new(module_path!(), ::zeroclaw_log::Action::Note)
                .with_outcome(::zeroclaw_log::EventOutcome::Unknown)
                .with_attrs(::serde_json::json!({
                    "alias": p.alias,
                    "config_path": &config_path,
                })),
            "provider_extra must be a JSON object (use TOML inline \
             table syntax, not a JSON string). Got: {extra}. Config path: {config_path}",
        );
    }
    if let Some(kwargs) = &opts.chat_template_kwargs
        && !kwargs.is_object()
    {
        let config_path = format!("[providers.models.{}].chat_template_kwargs", p.alias);
        ::zeroclaw_log::record!(
            WARN,
            ::zeroclaw_log::Event::new(module_path!(), ::zeroclaw_log::Action::Note)
                .with_outcome(::zeroclaw_log::EventOutcome::Unknown)
                .with_attrs(::serde_json::json!({
                    "alias": p.alias,
                    "config_path": &config_path,
                })),
            "chat_template_kwargs must be a JSON object (use TOML inline \
             table syntax). Got: {kwargs}. Config path: {config_path}",
        );
    }
    Box::new(p)
}

fn build_responses_provider_if_requested(
    wire_api: Option<zeroclaw_config::schema::WireApi>,
    alias: &str,
    base_url: Option<&str>,
    key: Option<&str>,
    opts: &ModelProviderRuntimeOptions,
) -> Option<Box<dyn ModelProvider>> {
    if wire_api != Some(zeroclaw_config::schema::WireApi::Responses) {
        return None;
    }
    let mut builder = crate::openai::OpenAiResponsesModelProvider::builder(alias).credential(key);
    if let Some(url) = base_url {
        builder = builder.api_url(url);
    }
    if let Some(t) = opts.provider_timeout_secs {
        builder = builder.timeout_secs(t);
    }
    if let Some(mt) = opts.provider_max_tokens {
        builder = builder.max_tokens(Some(mt));
    }
    if let Some(ref effort) = opts.reasoning_effort {
        builder = builder.reasoning_effort(Some(effort.clone()));
    }
    if !opts.extra_headers.is_empty() {
        builder = builder.extra_headers(opts.extra_headers.clone());
    }
    Some(Box::new(builder.build()))
}

pub fn dispatch_family_factory(
    config: Option<&zeroclaw_config::schema::Config>,
    family: &str,
    alias: &str,
    key: Option<&str>,
    api_url: Option<&str>,
    opts: &ModelProviderRuntimeOptions,
) -> Result<Box<dyn ModelProvider>> {
    // openai missing-entry fallback: see `openai_missing_entry_fallback_config`.
    // A persisted entry keeps its stored `wire_api`; an implicit dispatch with no
    // entry (bare `openai` ref or a dangling alias) stays on the chat-completions
    // wire so existing installs don't flip wire + tool-calling mode on upgrade.
    if family == "openai" {
        let default_cfg = openai_missing_entry_fallback_config();
        let cfg = config
            .and_then(|c| c.providers.models.openai.get(alias))
            .unwrap_or(&default_cfg);
        return cfg.create_provider(alias, key, api_url, opts);
    }
    macro_rules! emit_dispatch {
        ($(($field:ident, $type_str:literal, $cfg_ty:ty)),+ $(,)?) => {
            match family {
                "openai-compatible" | "openai_compatible" => {
                    let default_cfg = zeroclaw_config::schema::ModelProviderConfig::default();
                    let cfg = config
                        .and_then(|c| c.providers.models.find("openai", alias))
                        .unwrap_or(&default_cfg);
                    cfg.create_provider(alias, key, api_url, opts)
                }
                $(
                    $type_str => {
                        let default_cfg: $cfg_ty;
                        let cfg: &$cfg_ty = match config.and_then(|c| c.providers.models.$field.get(alias)) {
                            Some(c) => c,
                            None => {
                                default_cfg = <$cfg_ty>::default();
                                &default_cfg
                            }
                        };
                        cfg.create_provider(alias, key, api_url, opts)
                    }
                )+
                _ => {
                    ::zeroclaw_log::record!(
                        ERROR,
                        ::zeroclaw_log::Event::new(module_path!(), ::zeroclaw_log::Action::Reject)
                            .with_outcome(::zeroclaw_log::EventOutcome::Failure)
                            .with_attrs(::serde_json::json!({"family": family})),
                        "factory: unknown model_provider family"
                    );
                    Err(anyhow::Error::msg(format!(
                        "Unknown model_provider family: {family}. After the V2 to typed-family migration, \
                         only canonical family names are valid. Run `zeroclaw quickstart` to reconfigure, \
                         or set `[providers.models.custom.<alias>] uri = \"https://your-api.com\"` for \
                         OpenAI-compatible custom endpoints."
                    )))
                },
            }
        }
    }
    zeroclaw_config::for_each_model_provider_slot!(emit_dispatch)
}

pub(crate) fn fallback_auth_ready_for_alias(
    config: &zeroclaw_config::schema::Config,
    family: &str,
    alias: &str,
    key: Option<&str>,
    opts: &ModelProviderRuntimeOptions,
) -> bool {
    let provider_kind = opts
        .provider_kind
        .as_deref()
        .map(str::trim)
        .filter(|value| !value.is_empty())
        .unwrap_or(family);

    // openai missing-entry fallback: keep construction symmetric with
    // `dispatch_family_factory`. `wire_api` does not influence auth-readiness,
    // but constructing the same chat-anchored fallback avoids any future
    // divergence if that changes.
    if provider_kind == "openai" {
        let default_cfg = openai_missing_entry_fallback_config();
        let cfg = config
            .providers
            .models
            .openai
            .get(alias)
            .unwrap_or(&default_cfg);
        return cfg.fallback_auth_ready(key, opts);
    }

    macro_rules! emit_auth_ready {
        ($(($field:ident, $type_str:literal, $cfg_ty:ty)),+ $(,)?) => {
            match provider_kind {
                "openai-compatible" | "openai_compatible" => {
                    let default_cfg = zeroclaw_config::schema::ModelProviderConfig::default();
                    let cfg = config
                        .providers
                        .models
                        .find("openai", alias)
                        .unwrap_or(&default_cfg);
                    cfg.fallback_auth_ready(key, opts)
                }
                $(
                    $type_str => {
                        let default_cfg: $cfg_ty;
                        let cfg: &$cfg_ty = match config.providers.models.$field.get(alias) {
                            Some(c) => c,
                            None => {
                                default_cfg = <$cfg_ty>::default();
                                &default_cfg
                            }
                        };
                        cfg.fallback_auth_ready(key, opts)
                    }
                )+
                _ => has_api_key(key),
            }
        }
    }
    zeroclaw_config::for_each_model_provider_slot!(emit_auth_ready)
}

use zeroclaw_config::schema::{
    AnthropicModelProviderConfig, AuthMode, CustomModelProviderConfig, GeminiModelProviderConfig,
    HAILO_OLLAMA_DEFAULT_URI, HailoOllamaEndpoint, HailoOllamaModelProviderConfig,
    OllamaModelProviderConfig, OpenAIModelProviderConfig, OpenRouterModelProviderConfig,
};

#[must_use]
/// Resolve endpoint behavior for one canonical provider family.
pub fn endpoint_for_family(provider_type: &str) -> Option<ProviderEndpoint> {
    macro_rules! emit_endpoint {
        ($(($field:ident, $type_str:literal, $cfg_ty:ty)),+ $(,)?) => {
            match provider_type {
                $( $type_str => Some(<$cfg_ty as FamilyProviderFactory>::ENDPOINT), )+
                _ => None,
            }
        };
    }
    zeroclaw_config::for_each_model_provider_slot!(emit_endpoint)
}

/// Get the fixed default API URL for a canonical provider family.
#[deprecated(note = "use endpoint_for_family or default_model_provider_url")]
pub fn get_default_url(provider_type: &str) -> Option<&'static str> {
    endpoint_for_family(provider_type).and_then(ProviderEndpoint::fixed_url)
}

impl FamilyProviderFactory for OpenRouterModelProviderConfig {
    const ENDPOINT: ProviderEndpoint = ProviderEndpoint::Fixed(crate::openrouter::BASE_URL);

    fn create_provider(
        &self,
        alias: &str,
        key: Option<&str>,
        _api_url: Option<&str>,
        opts: &ModelProviderRuntimeOptions,
    ) -> Result<Box<dyn ModelProvider>> {
        let mut b = crate::openrouter::OpenRouterModelProvider::builder(alias)
            .credential(key)
            .max_tokens(opts.provider_max_tokens);
        if let Some(t) = opts.provider_timeout_secs {
            b = b.timeout_secs(t);
        }
        if let Some(extra) = opts.provider_extra.clone() {
            b = b.extra_body(extra);
        }
        Ok(Box::new(b.build()))
    }
}

impl FamilyProviderFactory for AnthropicModelProviderConfig {
    const ENDPOINT: ProviderEndpoint = ProviderEndpoint::Fixed(crate::anthropic::BASE_URL);

    fn create_provider(
        &self,
        alias: &str,
        key: Option<&str>,
        api_url: Option<&str>,
        opts: &ModelProviderRuntimeOptions,
    ) -> Result<Box<dyn ModelProvider>> {
        let mut b = crate::anthropic::AnthropicModelProvider::builder(alias)
            .credential(key)
            .server_fallback_models(self.server_fallback_models.clone())
            .base_url(api_url.unwrap_or(fixed_family_endpoint::<Self>()));
        if let Some(mt) = opts.provider_max_tokens {
            b = b.max_tokens(mt);
        }
        if let Some(ts) = opts.provider_timeout_secs {
            b = b.timeout_secs(ts);
        }
        if let Some(cache_ttl) = opts.cache_ttl {
            b = b.cache_ttl(cache_ttl);
        }
        Ok(Box::new(b.build()))
    }
}

/// Config used when the `openai` family is dispatched with **no persisted
/// entry** — a bare `model_provider = "openai"` reference or a dotted ref to a
/// nonexistent alias.
///
/// This deliberately differs from [`OpenAIModelProviderConfig::default`], which
/// selects the responses wire for *new persisted slots* created via
/// `create_map_key` / `ensure`. Implicit dispatch must instead leave `wire_api`
/// unset so it resolves to the historical chat-completions wire; otherwise an
/// existing install with a bare `openai` ref would silently flip both its wire
/// protocol and its tool-calling mode on upgrade, contradicting the
/// backward-compatibility guarantee. Persisted entries are never routed through
/// this helper — they keep whatever `wire_api` they stored.
fn openai_missing_entry_fallback_config() -> OpenAIModelProviderConfig {
    OpenAIModelProviderConfig {
        base: zeroclaw_config::schema::ModelProviderConfig {
            wire_api: None,
            ..zeroclaw_config::schema::ModelProviderConfig::default()
        },
    }
}

impl FamilyProviderFactory for OpenAIModelProviderConfig {
    const ENDPOINT: ProviderEndpoint = ProviderEndpoint::Dynamic;

    fn create_provider(
        &self,
        alias: &str,
        key: Option<&str>,
        api_url: Option<&str>,
        opts: &ModelProviderRuntimeOptions,
    ) -> Result<Box<dyn ModelProvider>> {
        // Codex variant routing: OAuth subscription auth → Codex responses protocol.
        if self.base.requires_openai_auth {
            return Ok(Box::new(
                crate::openai_codex::OpenAiCodexModelProvider::new(alias, opts, key)?,
            ));
        }
        // Responses wire protocol with standard API key — full streaming tool calls.
        // New OpenAI provider slots default wire_api to Responses via
        // OpenAIModelProviderConfig::default() (persisted-slot creation). Bare/
        // dangling dispatch uses openai_missing_entry_fallback_config() and stays
        // on the chat wire; unset/legacy configs also fall through below.
        if let Some(p) =
            build_responses_provider_if_requested(self.base.wire_api, alias, api_url, key, opts)
        {
            return Ok(p);
        }
        // Fallback: chat_completions wire (explicit opt-in or legacy unset configs).
        let mut b = crate::openai::OpenAiModelProvider::builder(alias).credential(key);
        if let Some(url) = api_url {
            b = b.base_url(url);
        }
        if let Some(t) = opts.provider_timeout_secs {
            b = b.timeout_secs(t);
        }
        if let Some(mt) = opts.provider_max_tokens {
            b = b.max_tokens(Some(mt));
        }
        Ok(Box::new(b.build()))
    }

    fn fallback_auth_ready(&self, key: Option<&str>, _opts: &ModelProviderRuntimeOptions) -> bool {
        has_api_key(key) || self.base.requires_openai_auth
    }
}

fn normalize_ollama_compat_base_url(api_url: Option<&str>) -> String {
    let raw = api_url
        .map(str::trim)
        .filter(|value| !value.is_empty())
        .unwrap_or(fixed_family_endpoint::<OllamaModelProviderConfig>());

    let Ok(mut url) = reqwest::Url::parse(raw) else {
        return raw.trim_end_matches('/').to_string();
    };

    let path = url.path().trim_end_matches('/');
    if path.is_empty() || matches!(path, "/" | "/api" | "/api/chat") {
        url.set_path("/v1");
        return url.to_string().trim_end_matches('/').to_string();
    }

    raw.trim_end_matches('/').to_string()
}

fn build_ollama_compat_provider(
    alias: &str,
    key: Option<&str>,
    api_url: Option<&str>,
    opts: &ModelProviderRuntimeOptions,
) -> crate::compatible::OpenAiCompatibleBuilder {
    let base_url = normalize_ollama_compat_base_url(api_url);
    let ollama_key = key.map(str::trim).filter(|value| !value.is_empty());
    let mut b = OpenAiCompatibleModelProvider::builder(alias)
        .display_name("Ollama")
        .base_url(&base_url)
        .canonical_base_url(OLLAMA_COMPAT_DEFAULT_URL)
        .credential(ollama_key)
        .auth_style(AuthStyle::Bearer)
        .vision(true)
        .local_model_tool_sanitize()
        .public_model_listing();
    if opts.merge_system_into_user {
        b = b.merge_system_into_user_preserving_native();
    }
    b
}

impl FamilyProviderFactory for OllamaModelProviderConfig {
    const ENDPOINT: ProviderEndpoint = ProviderEndpoint::Fixed(OLLAMA_COMPAT_DEFAULT_URL);

    fn create_provider(
        &self,
        alias: &str,
        key: Option<&str>,
        api_url: Option<&str>,
        opts: &ModelProviderRuntimeOptions,
    ) -> Result<Box<dyn ModelProvider>> {
        Ok(apply_compat_options(
            build_ollama_compat_provider(alias, key, api_url, opts),
            opts,
        ))
    }

    fn fallback_auth_ready(&self, _key: Option<&str>, _opts: &ModelProviderRuntimeOptions) -> bool {
        true
    }
}

impl FamilyProviderFactory for HailoOllamaModelProviderConfig {
    const ENDPOINT: ProviderEndpoint = ProviderEndpoint::Fixed(HAILO_OLLAMA_DEFAULT_URI);

    fn create_provider(
        &self,
        alias: &str,
        key: Option<&str>,
        api_url: Option<&str>,
        opts: &ModelProviderRuntimeOptions,
    ) -> Result<Box<dyn ModelProvider>> {
        use zeroclaw_config::schema::ModelEndpoint;

        if opts.tls_ca_cert_path.is_some() {
            anyhow::bail!("Hailo-Ollama does not support tls_ca_cert_path");
        }
        if opts.think == Some(true) {
            return Err(anyhow::Error::new(crate::ProviderCapabilityError {
                model_provider: alias.to_string(),
                capability: "thinking".to_string(),
                message: "Hailo-Ollama does not support think=true".to_string(),
            }));
        }
        if opts.vision == Some(true) {
            return Err(anyhow::Error::new(crate::ProviderCapabilityError {
                model_provider: alias.to_string(),
                capability: "vision".to_string(),
                message: "Hailo-Ollama does not support vision=true".to_string(),
            }));
        }
        if opts.provider_extra.is_some() {
            anyhow::bail!("Hailo-Ollama does not support provider_extra");
        }
        if opts.api_path.is_some() {
            anyhow::bail!("Hailo-Ollama does not support api_path");
        }
        if opts.wire_api.is_some() {
            anyhow::bail!("Hailo-Ollama does not support wire_api overrides");
        }
        if opts.chat_template_kwargs.is_some() {
            anyhow::bail!("Hailo-Ollama does not support chat_template_kwargs");
        }
        if opts.native_tools == Some(true) {
            return Err(anyhow::Error::new(crate::ProviderCapabilityError {
                model_provider: alias.to_string(),
                capability: "native_tools".to_string(),
                message: "Hailo-Ollama does not support native tool calling".to_string(),
            }));
        }

        let max_tokens = opts
            .provider_max_tokens
            .map_or(crate::hailo_ollama::HAILO_DEFAULT_NUM_PREDICT, |value| {
                i32::try_from(value).unwrap_or(i32::MAX)
            });
        let tuning = crate::ollama::OllamaTuning {
            num_ctx: self
                .base
                .context_window
                .map(|value| u32::try_from(value).unwrap_or(u32::MAX))
                .unwrap_or(crate::hailo_ollama::HAILO_DEFAULT_NUM_CTX),
            num_predict: max_tokens,
            temperature_override: None,
        };
        let endpoint = HailoOllamaEndpoint::default();
        let base_url = api_url.unwrap_or_else(|| endpoint.uri());
        Ok(Box::new(
            crate::hailo_ollama::HailoOllamaModelProvider::new(
                alias,
                Some(base_url),
                opts.provider_timeout_secs
                    .unwrap_or(zeroclaw_api::model_provider::BASELINE_TIMEOUT_SECS),
                self.queue_timeout_secs
                    .unwrap_or(crate::hailo_ollama::HAILO_DEFAULT_QUEUE_TIMEOUT_SECS),
                tuning,
            )?
            .with_auth_headers(key, &opts.extra_headers)?,
        ))
    }

    fn fallback_auth_ready(&self, _key: Option<&str>, _opts: &ModelProviderRuntimeOptions) -> bool {
        true
    }
}

impl FamilyProviderFactory for GeminiModelProviderConfig {
    const ENDPOINT: ProviderEndpoint = ProviderEndpoint::Dynamic;

    fn create_provider(
        &self,
        alias: &str,
        key: Option<&str>,
        _api_url: Option<&str>,
        opts: &ModelProviderRuntimeOptions,
    ) -> Result<Box<dyn ModelProvider>> {
        let state_dir = opts.zeroclaw_dir.clone().unwrap_or_else(|| {
            directories::UserDirs::new().map_or_else(
                || std::path::PathBuf::from(".zeroclaw"),
                |dirs| dirs.home_dir().join(".zeroclaw"),
            )
        });
        let auth_service = crate::auth::AuthService::new(&state_dir, opts.secrets_encrypt);
        Ok(Box::new(
            crate::gemini::GeminiModelProvider::builder(alias)
                .api_key(key)
                .managed_auth(auth_service, opts.auth_profile_override.clone())
                .oauth_project_seed(self.oauth_project.clone())
                .oauth_client(
                    self.oauth_client_id.clone(),
                    self.oauth_client_secret.clone(),
                )
                .build(),
        ))
    }

    fn fallback_auth_ready(&self, key: Option<&str>, _opts: &ModelProviderRuntimeOptions) -> bool {
        has_api_key(key) || matches!(self.auth_mode, Some(AuthMode::OAuth))
    }
}

// ── Kilo AI Gateway (OpenAI-compatible) ────────────────────────────────

impl FamilyProviderFactory for CustomModelProviderConfig {
    const ENDPOINT: ProviderEndpoint = ProviderEndpoint::OperatorRequired;

    fn create_provider(
        &self,
        alias: &str,
        key: Option<&str>,
        api_url: Option<&str>,
        opts: &ModelProviderRuntimeOptions,
    ) -> Result<Box<dyn ModelProvider>> {
        let base_url = api_url.ok_or_else(|| {
            ::zeroclaw_log::record!(
                ERROR,
                ::zeroclaw_log::Event::new(module_path!(), ::zeroclaw_log::Action::Reject)
                    .with_outcome(::zeroclaw_log::EventOutcome::Failure)
                    .with_attrs(::serde_json::json!({
                        "family": "custom",
                        "alias": alias,
                        "missing": "uri",
                    })),
                "factory: custom provider missing uri"
            );
            anyhow::Error::msg(
                "Custom model_provider requires `uri`: set \
                 `[providers.models.custom.<alias>] uri = \"https://your-api.com\"` in config.toml.",
            )
        })?;
        if let Some(p) = build_responses_provider_if_requested(
            self.base.wire_api,
            alias,
            Some(base_url),
            key,
            opts,
        ) {
            return Ok(p);
        }
        let mut b = OpenAiCompatibleModelProvider::builder(alias)
            .display_name("Custom")
            .base_url(base_url)
            .credential(key)
            .auth_style(AuthStyle::Bearer)
            .vision(true);
        if opts.native_tools != Some(true) {
            b = b.without_native_tools();
        }
        if opts.merge_system_into_user {
            b = b.merge_system_into_user_preserving_native();
        }
        Ok(apply_compat_options(b, opts))
    }

    fn fallback_auth_ready(&self, _key: Option<&str>, _opts: &ModelProviderRuntimeOptions) -> bool {
        true
    }
}

impl FamilyProviderFactory for zeroclaw_config::schema::ModelProviderConfig {
    const ENDPOINT: ProviderEndpoint = ProviderEndpoint::OperatorRequired;

    fn create_provider(
        &self,
        alias: &str,
        key: Option<&str>,
        api_url: Option<&str>,
        opts: &ModelProviderRuntimeOptions,
    ) -> Result<Box<dyn ModelProvider>> {
        let base_url = api_url.ok_or_else(|| {
            anyhow::Error::msg(
                "OpenAI-compatible model_provider requires `uri`: set \
                 `[providers.models.<family>.<alias>] uri = \"https://your-api.com\"` in config.toml.",
            )
        })?;
        if let Some(p) =
            build_responses_provider_if_requested(self.wire_api, alias, Some(base_url), key, opts)
        {
            return Ok(p);
        }
        let mut b = OpenAiCompatibleModelProvider::builder(alias)
            .display_name("OpenAI Compatible")
            .base_url(base_url)
            .credential(key)
            .auth_style(AuthStyle::Bearer)
            .vision(true);
        if opts.merge_system_into_user {
            b = b.merge_system_into_user_preserving_native();
        }
        Ok(apply_compat_options(b, opts))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use zeroclaw_config::schema::{ModelProviderConfig, WireApi};

    #[test]
    fn cache_passthrough_runtime_option_reaches_provider_capability() {
        let provider = apply_compat_options(
            OpenAiCompatibleModelProvider::builder("test")
                .display_name("custom")
                .base_url("http://127.0.0.1:1")
                .auth_style(AuthStyle::Bearer),
            &ModelProviderRuntimeOptions {
                cache_passthrough: true,
                ..ModelProviderRuntimeOptions::default()
            },
        );
        assert!(
            provider.capabilities().prompt_caching,
            "factory must thread cache_passthrough into the provider capability"
        );

        let default_provider = apply_compat_options(
            OpenAiCompatibleModelProvider::builder("test")
                .display_name("custom")
                .base_url("http://127.0.0.1:1")
                .auth_style(AuthStyle::Bearer),
            &ModelProviderRuntimeOptions::default(),
        );
        assert!(!default_provider.capabilities().prompt_caching);
    }

    /// D2a: `cache_ttl` must survive the factory boundary on both builders.
    /// The compatible half goes through `apply_compat_options` and the native
    /// half through `AnthropicModelProviderConfig::create_provider`; each
    /// drives a structured chat against a capture mock, so deleting the
    /// `with_cache_ttl` forwarding in `apply_compat_options` or the
    /// `cache_ttl` forwarding in `create_provider` fails this test (the
    /// markers lose their `ttl` field). The wire is the observation point
    /// because both factory functions return `Box<dyn ModelProvider>` and
    /// the configured lifetime has no trait-object readback.
    #[tokio::test]
    async fn cache_ttl_runtime_option_reaches_both_builders() {
        use crate::traits::{ChatMessage, ChatRequest};
        use zeroclaw_api::tool::ToolSpec;
        use zeroclaw_config::schema::{AnthropicModelProviderConfig, CacheTtl};

        fn collect_cache_controls(value: &serde_json::Value, out: &mut Vec<serde_json::Value>) {
            match value {
                serde_json::Value::Object(map) => {
                    if let Some(control) = map.get("cache_control") {
                        out.push(control.clone());
                    }
                    for nested in map.values() {
                        collect_cache_controls(nested, out);
                    }
                }
                serde_json::Value::Array(items) => {
                    for item in items {
                        collect_cache_controls(item, out);
                    }
                }
                _ => {}
            }
        }

        async fn compat_request(opts: &ModelProviderRuntimeOptions) -> serde_json::Value {
            use axum::{Json, Router, routing::post};
            use std::sync::{Arc, Mutex};
            use tokio::net::TcpListener;

            let captured: Arc<Mutex<Vec<serde_json::Value>>> = Arc::new(Mutex::new(Vec::new()));
            let captured_for_route = Arc::clone(&captured);
            let app = Router::new().route(
                "/chat/completions",
                post(move |Json(body): Json<serde_json::Value>| {
                    let captured = Arc::clone(&captured_for_route);
                    async move {
                        captured.lock().unwrap().push(body);
                        Json(serde_json::json!({
                            "choices": [{"message": {"content": "ok"}}]
                        }))
                    }
                }),
            );
            let listener = TcpListener::bind("127.0.0.1:0").await.unwrap();
            let addr = listener.local_addr().unwrap();
            let server = ::zeroclaw_spawn::spawn!(async move {
                axum::serve(listener, app).await.unwrap();
            });
            let provider = apply_compat_options(
                OpenAiCompatibleModelProvider::builder("test")
                    .display_name("custom")
                    .base_url(&format!("http://{addr}"))
                    .auth_style(AuthStyle::Bearer),
                opts,
            );
            let messages = vec![
                ChatMessage::system("be brief"),
                ChatMessage::user("first question"),
                ChatMessage::assistant("first answer"),
                ChatMessage::user("second question"),
            ];
            let result = provider
                .chat(
                    ChatRequest {
                        messages: &messages,
                        tools: None,
                        thinking: None,
                    },
                    "test-model",
                    None,
                )
                .await;
            server.abort();
            result.unwrap_or_else(|error| panic!("compat request failed: {error}"));
            let requests = captured.lock().unwrap();
            requests[0].clone()
        }

        async fn native_request(opts: &ModelProviderRuntimeOptions) -> serde_json::Value {
            use axum::{Json, Router, routing::post};
            use std::sync::{Arc, Mutex};
            use tokio::net::TcpListener;

            let captured: Arc<Mutex<Vec<serde_json::Value>>> = Arc::new(Mutex::new(Vec::new()));
            let captured_for_route = Arc::clone(&captured);
            let app = Router::new().route(
                "/v1/messages",
                post(move |Json(body): Json<serde_json::Value>| {
                    let captured = Arc::clone(&captured_for_route);
                    async move {
                        captured.lock().unwrap().push(body);
                        Json(serde_json::json!({
                            "id": "msg_ttl",
                            "type": "message",
                            "role": "assistant",
                            "content": [{"type": "text", "text": "ok"}],
                            "model": "claude-sonnet-4-5",
                            "stop_reason": "end_turn",
                            "usage": {"input_tokens": 10, "output_tokens": 2}
                        }))
                    }
                }),
            );
            let listener = TcpListener::bind("127.0.0.1:0").await.unwrap();
            let addr = listener.local_addr().unwrap();
            let server = ::zeroclaw_spawn::spawn!(async move {
                axum::serve(listener, app).await.unwrap();
            });
            let provider = AnthropicModelProviderConfig::default()
                .create_provider(
                    "anthropic",
                    Some("test-key"),
                    Some(&format!("http://{addr}")),
                    opts,
                )
                .expect("native anthropic provider constructs");
            let messages = vec![
                ChatMessage::system("You are a helpful assistant."),
                ChatMessage::user("gen a 2 sum in golang"),
                ChatMessage::assistant("```go\nfunc twoSum() {}\n```"),
                ChatMessage::user("what's meaning of make here?"),
            ];
            let tools = vec![ToolSpec::new(
                "shell",
                "Run a shell command",
                serde_json::json!({
                    "type": "object",
                    "properties": {"command": {"type": "string"}},
                    "required": ["command"]
                }),
            )];
            let result = provider
                .chat(
                    ChatRequest {
                        messages: &messages,
                        tools: Some(&tools),
                        thinking: None,
                    },
                    "claude-sonnet-4-5",
                    Some(0.7),
                )
                .await;
            server.abort();
            result.unwrap_or_else(|error| panic!("native request failed: {error}"));
            let requests = captured.lock().unwrap();
            requests[0].clone()
        }

        let ttl_opts = ModelProviderRuntimeOptions {
            cache_ttl: Some(CacheTtl::OneHour),
            cache_passthrough: true,
            ..ModelProviderRuntimeOptions::default()
        };

        let compat_one_hour = compat_request(&ttl_opts).await;
        let mut controls = Vec::new();
        collect_cache_controls(&compat_one_hour, &mut controls);
        assert_eq!(
            controls.len(),
            2,
            "system + rolling breakpoints expected: {compat_one_hour}"
        );
        for control in &controls {
            assert_eq!(
                control["ttl"], "1h",
                "apply_compat_options must forward cache_ttl: {compat_one_hour}"
            );
        }

        let compat_default = compat_request(&ModelProviderRuntimeOptions::default()).await;
        let mut controls = Vec::new();
        collect_cache_controls(&compat_default, &mut controls);
        assert!(
            controls.is_empty(),
            "default options must place no cache_control: {compat_default}"
        );

        let native_one_hour = native_request(&ttl_opts).await;
        let mut controls = Vec::new();
        collect_cache_controls(&native_one_hour, &mut controls);
        assert_eq!(
            controls.len(),
            3,
            "system + tools + rolling markers expected: {native_one_hour}"
        );
        for control in &controls {
            assert_eq!(
                control["ttl"], "1h",
                "create_provider must forward cache_ttl: {native_one_hour}"
            );
        }

        let native_default = native_request(&ModelProviderRuntimeOptions::default()).await;
        let mut controls = Vec::new();
        collect_cache_controls(&native_default, &mut controls);
        assert_eq!(controls.len(), 3, "marker placement is unconditional");
        for control in &controls {
            assert_eq!(
                serde_json::to_string(control).unwrap(),
                r#"{"type":"ephemeral"}"#,
                "default options keep the pre-TTL native wire form: {native_default}"
            );
        }
    }

    #[test]
    fn endpoint_registry_classifies_every_canonical_family() {
        macro_rules! collect_names {
            ($(($field:ident, $type_str:literal, $cfg_ty:ty)),+ $(,)?) => {
                [$($type_str),+]
            };
        }
        let families = zeroclaw_config::for_each_model_provider_slot!(collect_names);

        for family in families {
            assert!(
                endpoint_for_family(family).is_some(),
                "canonical provider {family:?} is missing endpoint metadata"
            );
        }
        assert!(endpoint_for_family("not_a_provider").is_none());
        assert!(endpoint_for_family("openai-compatible").is_none());
        assert!(endpoint_for_family("openai_compatible").is_none());
    }

    #[test]
    fn every_fixed_endpoint_constructs_without_an_override() {
        macro_rules! assert_fixed_construction {
            ($(($field:ident, $type_str:literal, $cfg_ty:ty)),+ $(,)?) => {{
                let opts = ModelProviderRuntimeOptions::default();
                $(
                    if let ProviderEndpoint::Fixed(url) =
                        <$cfg_ty as FamilyProviderFactory>::ENDPOINT
                    {
                        let config = <$cfg_ty>::default();
                        let provider = config
                            .create_provider($type_str, Some("test-key"), None, &opts)
                            .unwrap_or_else(|error| {
                                panic!(
                                    "fixed provider family {:?} did not construct from its canonical endpoint: {error:#}",
                                    $type_str
                                )
                            });
                        assert_eq!(
                            provider.default_base_url(),
                            Some(url),
                            "fixed provider family {:?} constructed a different default endpoint",
                            $type_str
                        );
                    }
                )+
            }};
        }

        zeroclaw_config::for_each_model_provider_slot!(assert_fixed_construction);
    }

    #[test]
    fn endpoint_registry_matches_independent_non_fixed_oracle() {
        assert_eq!(
            endpoint_for_family("openrouter"),
            Some(ProviderEndpoint::Fixed("https://openrouter.ai/api/v1"))
        );
        for family in ["openai", "gemini"] {
            assert_eq!(
                endpoint_for_family(family),
                Some(ProviderEndpoint::Dynamic),
                "{family} selects its endpoint at runtime"
            );
        }
        assert_eq!(
            endpoint_for_family("custom"),
            Some(ProviderEndpoint::OperatorRequired),
            "custom requires operator endpoint input"
        );
    }

    #[test]
    fn merge_extra_body_nests_chat_template_kwargs_under_own_key() {
        let kwargs = serde_json::json!({"thinking": true, "reasoning_effort": "max"});
        let merged = merge_extra_body(None, Some(&kwargs))
            .expect("chat_template_kwargs alone must produce an extra_body object");
        assert_eq!(
            merged.get("chat_template_kwargs"),
            Some(&kwargs),
            "chat_template_kwargs must be nested under its own top-level key"
        );
    }

    #[test]
    fn merge_extra_body_combines_provider_extra_and_chat_template_kwargs() {
        let provider_extra = serde_json::json!({"top_p": 0.95});
        let kwargs = serde_json::json!({"thinking": true});
        let merged = merge_extra_body(Some(&provider_extra), Some(&kwargs))
            .expect("both sources present must produce an extra_body object");
        assert_eq!(
            merged.get("top_p").and_then(serde_json::Value::as_f64),
            Some(0.95),
            "provider_extra keys must remain at the top level"
        );
        assert_eq!(
            merged.get("chat_template_kwargs"),
            Some(&kwargs),
            "chat_template_kwargs must coexist with provider_extra keys"
        );
    }

    #[test]
    fn merge_extra_body_ignores_non_object_provider_extra() {
        let provider_extra = serde_json::json!("not-an-object");
        assert!(
            merge_extra_body(Some(&provider_extra), None).is_none(),
            "a non-object provider_extra with no chat_template_kwargs must yield None"
        );
    }

    #[test]
    fn merge_extra_body_ignores_non_object_chat_template_kwargs() {
        // Scalars, arrays, and null are not valid chat-template payloads; drop
        // them the same way provider_extra drops non-object shapes.
        for shape in [
            serde_json::json!("max"),
            serde_json::json!(true),
            serde_json::json!(["a", "b"]),
            serde_json::Value::Null,
        ] {
            assert!(
                merge_extra_body(None, Some(&shape)).is_none(),
                "a non-object chat_template_kwargs ({shape}) must be dropped, yielding None"
            );
        }
    }

    #[test]
    fn merge_extra_body_is_none_when_both_absent() {
        assert!(
            merge_extra_body(None, None).is_none(),
            "no extras must yield None so the caller skips extra_body"
        );
    }

    #[test]
    fn openai_factory_routes_to_codex_when_requires_openai_auth_true() {
        let cfg = OpenAIModelProviderConfig {
            base: ModelProviderConfig {
                requires_openai_auth: true,
                ..Default::default()
            },
        };
        let provider = cfg
            .create_provider("test", None, None, &ModelProviderRuntimeOptions::default())
            .unwrap();
        // OpenAiCodexModelProvider reports native_tool_calling; standard OpenAiModelProvider does not
        assert!(provider.capabilities().native_tool_calling);
    }

    #[test]
    fn openai_factory_routes_to_standard_when_requires_openai_auth_false() {
        // Explicit chat_completions: OpenAIModelProviderConfig::default() now
        // selects the responses wire, so this regression pins the legacy path.
        let cfg = OpenAIModelProviderConfig {
            base: ModelProviderConfig {
                requires_openai_auth: false,
                wire_api: Some(WireApi::ChatCompletions),
                ..Default::default()
            },
        };
        let provider = cfg
            .create_provider("test", None, None, &ModelProviderRuntimeOptions::default())
            .unwrap();
        assert!(!provider.capabilities().native_tool_calling);
    }

    #[test]
    fn openai_factory_defaults_new_provider_to_responses_wire() {
        // Creating a new OpenAI provider slot (create_map_key / ensure) uses
        // OpenAIModelProviderConfig::default(), which must select responses.
        let provider = OpenAIModelProviderConfig::default()
            .create_provider(
                "test",
                Some("sk-test"),
                None,
                &ModelProviderRuntimeOptions::default(),
            )
            .unwrap();
        assert_eq!(provider.default_wire_api(), "responses");
        assert!(provider.capabilities().native_tool_calling);
    }

    #[test]
    fn openai_dispatch_missing_entry_stays_on_chat_wire() {
        // The responses default applies only to persisted slot creation. An implicit
        // dispatch with no config entry — a bare `model_provider = "openai"` ref or
        // a dangling alias —
        // must keep the historical chat-completions wire and prompt-guided tools,
        // so existing installs don't silently flip wire + tool-calling on upgrade.
        let provider = dispatch_family_factory(
            None,
            "openai",
            "default",
            Some("sk-test"),
            None,
            &ModelProviderRuntimeOptions::default(),
        )
        .expect("bare openai dispatch should build");
        assert_eq!(
            provider.default_wire_api(),
            "chat_completions",
            "missing-entry openai dispatch must not adopt the responses wire"
        );
        assert!(
            !provider.capabilities().native_tool_calling,
            "missing-entry openai dispatch must keep prompt-guided tool calling"
        );
    }

    #[test]
    fn openai_dispatch_persisted_entry_honors_responses_default() {
        // The counterpart to the missing-entry test: a persisted openai slot that
        // stored wire_api = responses (as create_map_key now writes) still routes
        // through the responses provider when dispatched.
        let mut config = zeroclaw_config::schema::Config::default();
        config.providers.models.openai.insert(
            "default".to_string(),
            OpenAIModelProviderConfig {
                base: ModelProviderConfig {
                    wire_api: Some(WireApi::Responses),
                    ..Default::default()
                },
            },
        );
        let provider = dispatch_family_factory(
            Some(&config),
            "openai",
            "default",
            Some("sk-test"),
            None,
            &ModelProviderRuntimeOptions::default(),
        )
        .expect("persisted openai dispatch should build");
        assert_eq!(provider.default_wire_api(), "responses");
        assert!(provider.capabilities().native_tool_calling);
    }

    #[tokio::test]
    async fn openai_factory_forwards_timeout_to_native_provider() {
        use axum::{Json, Router, routing::post};
        use serde_json::json;
        use tokio::time::{Duration, Instant};

        async fn slow_chat_completion() -> Json<serde_json::Value> {
            tokio::time::sleep(Duration::from_secs(3)).await;
            Json(json!({
                "choices": [{"message": {"content": "too late"}}]
            }))
        }

        let listener = tokio::net::TcpListener::bind("127.0.0.1:0")
            .await
            .expect("bind test server");
        let addr = listener.local_addr().expect("test server addr");
        let app = Router::new().route("/chat/completions", post(slow_chat_completion));
        let server = zeroclaw_spawn::spawn!(async move {
            axum::serve(listener, app).await.expect("serve test server");
        });

        let opts = ModelProviderRuntimeOptions {
            provider_timeout_secs: Some(1),
            ..Default::default()
        };
        // Pin the chat-completions path explicitly: OpenAI defaults to responses.
        let provider = OpenAIModelProviderConfig {
            base: ModelProviderConfig {
                wire_api: Some(WireApi::ChatCompletions),
                ..Default::default()
            },
        }
        .create_provider(
            "native",
            Some("test-key"),
            Some(&format!("http://{addr}")),
            &opts,
        )
        .expect("openai provider should build");

        let started = Instant::now();
        let result = provider
            .chat_with_system(None, "hello", "gpt-4o", Some(0.7))
            .await;
        let elapsed = started.elapsed();

        server.abort();

        assert!(
            result.is_err(),
            "slow response should time out when factory forwards provider_timeout_secs"
        );
        assert!(
            elapsed < Duration::from_secs(3),
            "request waited for the server response instead of using configured timeout: {elapsed:?}"
        );
    }

    #[test]
    fn ollama_factory_uses_no_credential_when_key_absent() {
        let provider = build_ollama_compat_provider(
            "default",
            None,
            Some("http://192.168.1.100:11434/v1"),
            &ModelProviderRuntimeOptions::default(),
        )
        .build();

        assert_eq!(provider.name, "Ollama");
        assert_eq!(provider.base_url, "http://192.168.1.100:11434/v1");
        assert!(provider.credential.is_none());
    }

    #[test]
    fn ollama_factory_normalizes_host_root_to_openai_compat_base() {
        let provider = build_ollama_compat_provider(
            "default",
            None,
            Some("http://192.168.1.100:11434"),
            &ModelProviderRuntimeOptions::default(),
        )
        .build();

        assert_eq!(provider.base_url, "http://192.168.1.100:11434/v1");
    }

    #[test]
    fn ollama_factory_normalizes_legacy_api_path_to_openai_compat_base() {
        let provider = build_ollama_compat_provider(
            "default",
            None,
            Some("https://ollama.com/api"),
            &ModelProviderRuntimeOptions::default(),
        )
        .build();

        assert_eq!(provider.base_url, "https://ollama.com/v1");
    }

    #[test]
    fn ollama_factory_preserves_typed_api_key_for_official_cloud() {
        let provider = build_ollama_compat_provider(
            "default",
            Some("  ollama-key  "),
            Some("https://ollama.com/v1"),
            &ModelProviderRuntimeOptions::default(),
        )
        .build();

        assert_eq!(provider.credential.as_deref(), Some("ollama-key"));
    }

    #[test]
    fn custom_factory_routes_to_responses_provider_when_wire_api_responses() {
        use zeroclaw_config::schema::{CustomModelProviderConfig, ModelProviderConfig, WireApi};
        let cfg = CustomModelProviderConfig {
            base: ModelProviderConfig {
                uri: Some("http://10.0.0.15:8000/v1".to_string()),
                wire_api: Some(WireApi::Responses),
                ..Default::default()
            },
        };
        let provider = cfg
            .create_provider(
                "vllm",
                None,
                Some("http://10.0.0.15:8000/v1"),
                &ModelProviderRuntimeOptions::default(),
            )
            .unwrap();
        assert_eq!(provider.default_wire_api(), "responses");
    }

    #[test]
    fn custom_factory_defaults_to_chat_completions_without_wire_api() {
        use zeroclaw_config::schema::{CustomModelProviderConfig, ModelProviderConfig};
        let cfg = CustomModelProviderConfig {
            base: ModelProviderConfig {
                uri: Some("http://10.0.0.15:8000/v1".to_string()),
                ..Default::default()
            },
        };
        let provider = cfg
            .create_provider(
                "vllm",
                None,
                Some("http://10.0.0.15:8000/v1"),
                &ModelProviderRuntimeOptions::default(),
            )
            .unwrap();
        assert_ne!(provider.default_wire_api(), "responses");
    }

    #[tokio::test]
    async fn responses_factory_forwards_timeout_secs_to_responses_provider() {
        use axum::{Json, Router, routing::post};
        use serde_json::json;
        use tokio::time::{Duration, Instant};
        use zeroclaw_config::schema::{CustomModelProviderConfig, ModelProviderConfig, WireApi};

        async fn slow_responses() -> Json<serde_json::Value> {
            tokio::time::sleep(Duration::from_secs(3)).await;
            Json(json!({
                "id": "resp_slow",
                "object": "response",
                "output": [{"type": "message", "content": [{"type": "output_text", "text": "too late"}]}],
            }))
        }

        let listener = tokio::net::TcpListener::bind("127.0.0.1:0")
            .await
            .expect("bind test server");
        let addr = listener.local_addr().expect("test server addr");
        let app = Router::new().route("/v1/responses", post(slow_responses));
        let server = zeroclaw_spawn::spawn!(async move {
            axum::serve(listener, app).await.expect("serve test server");
        });

        let cfg = CustomModelProviderConfig {
            base: ModelProviderConfig {
                uri: Some(format!("http://{addr}/v1")),
                wire_api: Some(WireApi::Responses),
                ..Default::default()
            },
        };
        let opts = ModelProviderRuntimeOptions {
            provider_timeout_secs: Some(1),
            ..Default::default()
        };
        let provider = cfg
            .create_provider(
                "vllm",
                Some("test-key"),
                Some(&format!("http://{addr}/v1")),
                &opts,
            )
            .expect("openai responses provider should build");

        // Sanity-check routing + URL composition.
        assert_eq!(
            provider.default_wire_api(),
            "responses",
            "factory should route to the responses provider when wire_api=Responses"
        );
        assert_eq!(
            provider.default_base_url(),
            Some(format!("http://{addr}/v1/responses").as_str()),
            "factory-composed URL must end with /responses"
        );

        let started = Instant::now();
        let result = provider
            .chat_with_system(None, "hello", "gpt-5", Some(0.7))
            .await;
        let elapsed = started.elapsed();

        server.abort();

        assert!(
            result.is_err(),
            "slow response should time out when factory forwards provider_timeout_secs (1s)"
        );
        assert!(
            elapsed < Duration::from_secs(3),
            "request waited for the server response instead of using configured 1s timeout: {elapsed:?}"
        );
    }

    #[tokio::test]
    async fn responses_factory_forwards_extra_headers_to_responses_provider() {
        use axum::{Json, Router, extract::State, http::HeaderMap, routing::post};
        use serde_json::json;
        use std::collections::HashMap;
        use std::sync::{Arc, Mutex};
        use zeroclaw_config::schema::{CustomModelProviderConfig, ModelProviderConfig, WireApi};

        let captured: Arc<Mutex<Option<HeaderMap>>> = Arc::new(Mutex::new(None));

        async fn capture_headers(
            State(captured): State<Arc<Mutex<Option<HeaderMap>>>>,
            headers: HeaderMap,
        ) -> Json<serde_json::Value> {
            *captured.lock().expect("captured headers mutex") = Some(headers);
            Json(json!({
                "id": "resp_ok",
                "object": "response",
                "output": [{"type": "message", "content": [{"type": "output_text", "text": "ok"}]}],
            }))
        }

        let listener = tokio::net::TcpListener::bind("127.0.0.1:0")
            .await
            .expect("bind test server");
        let addr = listener.local_addr().expect("test server addr");
        let app = Router::new()
            .route("/v1/responses", post(capture_headers))
            .with_state(Arc::clone(&captured));
        let server = zeroclaw_spawn::spawn!(async move {
            axum::serve(listener, app).await.expect("serve test server");
        });

        let cfg = CustomModelProviderConfig {
            base: ModelProviderConfig {
                uri: Some(format!("http://{addr}/v1")),
                wire_api: Some(WireApi::Responses),
                ..Default::default()
            },
        };
        let mut extra_headers = HashMap::new();
        // The two non-reserved custom headers we expect to see on the wire.
        extra_headers.insert("X-Trace-Id".to_string(), "trace-abc-123".to_string());
        extra_headers.insert("X-Tenant".to_string(), "acme".to_string());
        // The reserved-header case we expect the factory to drop — the
        // built-in `Bearer test-key` (from `Some("test-key")` below) must be
        // the only Authorization value on the request.
        extra_headers.insert(
            "Authorization".to_string(),
            "Bearer should-be-dropped".to_string(),
        );
        // And the case-insensitive variant — must be dropped by the same
        // case-insensitive check in `build_default_headers`.
        extra_headers.insert(
            "authorization".to_string(),
            "Bearer lower-case-should-also-be-dropped".to_string(),
        );
        let opts = ModelProviderRuntimeOptions {
            extra_headers,
            ..Default::default()
        };
        let provider = cfg
            .create_provider(
                "vllm",
                Some("test-key"),
                Some(&format!("http://{addr}/v1")),
                &opts,
            )
            .expect("openai responses provider should build");

        let result = provider
            .chat_with_system(None, "hello", "gpt-5", Some(0.7))
            .await;

        server.abort();

        assert!(result.is_ok(), "fast response should succeed: {result:?}");

        let captured_headers = captured
            .lock()
            .expect("captured headers mutex")
            .clone()
            .expect("server handler must have captured the request headers");

        // (a) configured custom headers arrive on the wire.
        assert_eq!(
            captured_headers
                .get("X-Trace-Id")
                .map(|v| v.to_str().unwrap()),
            Some("trace-abc-123"),
            "configured extra_headers['X-Trace-Id'] must reach the wire"
        );
        assert_eq!(
            captured_headers
                .get("X-Tenant")
                .map(|v| v.to_str().unwrap()),
            Some("acme"),
            "configured extra_headers['X-Tenant'] must reach the wire"
        );

        let auth_values: Vec<&str> = captured_headers
            .get_all("Authorization")
            .iter()
            .filter_map(|v| v.to_str().ok())
            .collect();
        assert_eq!(
            auth_values.len(),
            1,
            "exactly one Authorization header must reach the wire; got {auth_values:?}"
        );
        assert_eq!(
            auth_values[0], "Bearer test-key",
            "the surviving Authorization must be the built-in bearer credential, not the dropped extra_headers entry"
        );
    }

    #[test]
    fn custom_factory_disables_native_tools_by_default() {
        use zeroclaw_config::schema::{CustomModelProviderConfig, ModelProviderConfig};
        let cfg = CustomModelProviderConfig {
            base: ModelProviderConfig {
                uri: Some("http://10.0.0.15:8000/v1".to_string()),
                ..Default::default()
            },
        };
        let provider = cfg
            .create_provider(
                "vllm",
                None,
                Some("http://10.0.0.15:8000/v1"),
                &ModelProviderRuntimeOptions::default(),
            )
            .unwrap();
        assert!(
            !provider.supports_native_tools(),
            "custom OpenAI-compatible endpoints must default to prompt-guided tools"
        );
    }

    #[test]
    fn custom_factory_honors_native_tools_override_true() {
        use zeroclaw_config::schema::{CustomModelProviderConfig, ModelProviderConfig};
        let cfg = CustomModelProviderConfig {
            base: ModelProviderConfig {
                uri: Some("http://10.0.0.15:8000/v1".to_string()),
                ..Default::default()
            },
        };
        let options = ModelProviderRuntimeOptions {
            native_tools: Some(true),
            ..Default::default()
        };
        let provider = cfg
            .create_provider("vllm", None, Some("http://10.0.0.15:8000/v1"), &options)
            .unwrap();
        assert!(
            provider.supports_native_tools(),
            "custom endpoints with `native_tools = true` must keep native tool calling available"
        );
    }

    #[test]
    fn openai_compatible_factory_routes_to_responses_when_wire_api_responses() {
        use zeroclaw_config::schema::{ModelProviderConfig, WireApi};
        let cfg = ModelProviderConfig {
            uri: Some("http://10.0.0.15:8000/v1".to_string()),
            wire_api: Some(WireApi::Responses),
            ..Default::default()
        };
        let provider = cfg
            .create_provider(
                "default",
                None,
                Some("http://10.0.0.15:8000/v1"),
                &ModelProviderRuntimeOptions::default(),
            )
            .unwrap();
        assert_eq!(provider.default_wire_api(), "responses");
    }
}
